name: Auto Contribution Commit with GPG

on:
  schedule:
    - cron: '0 23 * * *'  # 11 PM UTC = 4:30 AM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git Identity
        run: |
          git config user.name "itxadii"
          git config user.email "itzzsecure@gmail.com"

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --batch --passphrase "$GPG_PASSPHRASE" --import private.key
          rm private.key
          # Get key ID
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '$1 == "sec" {print $5}' | head -n1)
          echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
          # Configure Git to use this key
          git config --global user.signingkey "$KEY_ID"

      - name: Update contribution file
        run: |
          echo "🟢 $(date -u)" >> AUTOMATED_CONTRIBUTIONS.md
          echo "Commit time: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git add AUTOMATED_CONTRIBUTIONS.md
          git commit -S -m "chore: auto commit at $(date -u)" || exit 0
          git push
