name: 🚀 Auto Daily Contribution

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 5:30 AM IST every day (00:00 UTC)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Git Identity
      run: |
        git config user.name "itxadii"
        git config user.email "itzzsecure@gmail.com"

    - name: Make a change to trigger contribution
      run: |
        echo "Last updated on $(TZ='Asia/Kolkata' date)" > AUTOMATED_CONTRIBUTIONS.md

    - name: Commit & Push
      run: |
        git add AUTOMATED_CONTRIBUTIONS.md
        git commit -m "chore: update contributions on $(date -u)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

