name: Auto Commit with Verified Signing

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git Identity
        run: |
          git config user.name "itxadii"
          git config user.email "itzzsecure@gmail.com"

      - name: Update contribution file
        run: |
          echo "🟢 $(date -u)" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push with GPG Signing
        uses: crazymykl/gh-commit-sign@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          files: AUTOMATED_CONTRIBUTIONS.md
          commit_message: "chore: auto commit at $(date -u)"
          name: itxadii
          email: itzzsecure@gmail.com
