name: Auto Contribution Commit

on:
  schedule:
    - cron: '0 23 * * *'  # 11 PM UTC = 4:30 AM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Git identity
        run: |
          git config user.name "itxadii"
          git config user.email "itzzsecure@gmail.com"

      - name: Update contribution file
        run: echo "🟢 $(date -u)" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git add AUTOMATED_CONTRIBUTIONS.md
          git commit --author="itxadii <itzzsecure@gmail.com>" -m "chore: auto commit at $(date -u)" || exit 0
          git push
