name: Auto Contribution Commit with Verified GPG Signing

on:
  schedule:
    - cron: '0 23 * * *'  # 11 PM UTC = 4:30 AM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git Identity
        run: |
          git config user.name "itxadii"
          git config user.email "itzzsecure@gmail.com"

      - name: Setup GPG Environment
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # Get key ID
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec:/ {print $5}' | head -n1)
          echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
          # Configure Git signing
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true

      - name: Cache GPG Passphrase
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Cache passphrase using gpg-preset-passphrase
          KEYGRIP=$(gpg --list-secret-keys --with-keygrip --with-colons | awk -F: '/^grp:/ {print $10}' | head -n1)
          /usr/lib/gnupg/gpg-preset-passphrase --preset -P "$GPG_PASSPHRASE" "$KEYGRIP"

      - name: Update contribution file
        run: |
          echo "🟢 $(date -u)" >> AUTOMATED_CONTRIBUTIONS.md
          echo "Verified commit: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git add AUTOMATED_CONTRIBUTIONS.md
          git commit -S -m "chore: auto commit at $(date -u)" || exit 0
          git push
