name: Auto Contribution Commit

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every day at 11:00 PM UTC (4:30 AM IST)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Crucial: Use PAT for checkout

      - name: Set Git identity
        run: |
          git config user.name "itxadii"
          git config user.email "itzzsecure@gmail.com"  # Must match your GitHub verified email

      - name: Update contribution file
        run: |
          echo "🟢 $(date -u)" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git add AUTOMATED_CONTRIBUTIONS.md
          git commit -m "chore: auto commit at $(date -u)" || exit 0
          git push

