name: contribution-streak-maintainer

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 22 * * *" # Runs daily at 3:30 AM IST (22:00 UTC)

permissions:
  contents: write # Needed to make commits

jobs:
  maintain-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Make a contribution
        run: |
          npx contribution-streak-maintainer itxadii/Streak \
            --email=163154088+itxadii@users.noreply.github.com \
            --token=${{ secrets.GITHUB_TOKEN }}



