name: Automated GitHub Contributions

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every day at 11:00 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --global user.name "itxadii"
          git config --global user.email "itzzsecure@gmail.com"

      - name: Update contribution file
        run: |
          echo "✅ Auto Commit: $(date)" >> AUTOMATED_CONTRIBUTIONS.md

      - name: Commit and Push
        run: |
          git add AUTOMATED_CONTRIBUTIONS.md
          git commit -m "chore: auto update at $(date -u)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push


